version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
  - package_manager: "javascript"
    directory: "/components"
    update_schedule: "daily"
